### ISSUE TITLE
buildVFs.sh fails

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-sans-pro#168]
I assume this has to do with the latest progress of how the `features.fea` files w/ include statements are processed.

**Comment by miguelsousa** [comment]
How does it fall?

**Comment by miguelsousa** [comment]
Paul made changes in the master branch after the last release tag. Try checking out the last commit on January 11 2019, and let me know if it still fails.

**Comment by frankrolf** [comment]
In the latest master commit, running `./buildVFs.sh` fails like this:

```
source-sans-pro$ ./buildVFs.sh
SourceSansVariable-Roman
Generating temp UFO master(s)...
Building local otf's for master font paths...
makeotf [Note] Using features file at '/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_0/SourceSans_ExtraLight.temp.ufo/features.fea'.
makeotf [Note] setting the USE_TYPO_METRICS OS/2 fsSelection bit 7 from fontinfo keyword.
makeotf [Note] setting the WEIGHT_WIDTH_SLOPE_ONLY OS/2 fsSelection bit 8 from fontinfo keyword.
makeotf [Note] setting the OBLIQUE OS/2 fsSelection bit 9 from fontinfo keyword.
makeotfexe [FATAL] <SourceSansVariable-Roman> include file <../../familyVersion.fea> not found [SourceSans_ExtraLight.temp.ufo/../../../../familyTables.fea 2]
makeotf [Error] Failed to build output font file 'SourceSans_ExtraLight.otf'.

Error building OTF font for /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_0/SourceSans_ExtraLight.temp.ufo makeotf [Note] Using features file at '/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_0/SourceSans_ExtraLight.temp.ufo/features.fea'.
makeotf [Note] setting the USE_TYPO_METRICS OS/2 fsSelection bit 7 from fontinfo keyword.
makeotf [Note] setting the WEIGHT_WIDTH_SLOPE_ONLY OS/2 fsSelection bit 8 from fontinfo keyword.
makeotf [Note] setting the OBLIQUE OS/2 fsSelection bit 9 from fontinfo keyword.
makeotfexe [FATAL] <SourceSansVariable-Roman> include file <../../familyVersion.fea> not found [SourceSans_ExtraLight.temp.ufo/../../../../familyTables.fea 2]
makeotf [Error] Failed to build output font file 'SourceSans_ExtraLight.otf'.

makeotf cmd was 'makeotf -nshw -f "SourceSans_ExtraLight.temp.ufo" -o "SourceSans_ExtraLight.otf" -r -nS  2>&1' in /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_0.
makeotf [Note] Using features file at '/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_1/SourceSans_Black.temp.ufo/features.fea'.
makeotfexe [FATAL] <SourceSans_Black> include file <../../familyVersion.fea> not found [SourceSans_Black.temp.ufo/../../../../familyTables.fea 2]
makeotf [Error] Failed to build output font file 'SourceSans_Black.otf'.

Error building OTF font for /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_1/SourceSans_Black.temp.ufo makeotf [Note] Using features file at '/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_1/SourceSans_Black.temp.ufo/features.fea'.
makeotfexe [FATAL] <SourceSans_Black> include file <../../familyVersion.fea> not found [SourceSans_Black.temp.ufo/../../../../familyTables.fea 2]
makeotf [Error] Failed to build output font file 'SourceSans_Black.otf'.

makeotf cmd was 'makeotf -nshw -f "SourceSans_Black.temp.ufo" -o "SourceSans_Black.otf" -r -nS  2>&1' in /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_1.
Traceback (most recent call last):
  File "/usr/local/bin/buildcff2vf", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/afdko/buildcff2vf.py", line 989, in run
    otfFinder, exclude=("CFF2",))
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 779, in build
    master_fonts = load_masters(designspace, master_finder)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 893, in load_masters
    master.font = font = _open_font(master.path, master_finder)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 852, in _open_font
    raise VarLibError("Invalid master path: %r" % master_path)
fontTools.varLib.VarLibError: Invalid master path: '/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_0/SourceSans_ExtraLight.otf'
Subroutinizing SourceSansVariable-Roman.otf
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.otf]
INFO:ufo2ft:Pre-processing glyphs
ERROR:cu2qu.ufo:Glyphs named 'kai' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'careof' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'aturned.b' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'Dhook' have incompatible segment types:
  9: ('curve', 'line')
ERROR:cu2qu.ufo:Glyphs named 'aogonek.b' have incompatible segment types:
   4: ('curve', 'line')
   6: ('line', 'curve')
   8: ('curve', 'line')
   9: ('line', 'curve')
  15: ('curve', 'line')
  20: ('line', 'curve')
ERROR:cu2qu.ufo:Glyphs named 'Dhook.sc' have incompatible segment types:
  9: ('curve', 'line')
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontmake/__main__.py", line 395, in main
    project.run_from_designspace(designspace_path, **args)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 865, in run_from_designspace
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 919, in _run_from_designspace_interpolatable
    ttf_designspace = self.build_interpolatable_ttfs(designspace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 333, in build_interpolatable_ttfs
    return self._build_interpolatable_masters(designspace, ttf=True, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 318, in _build_interpolatable_masters
    inplace=True,
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 338, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 234, in compileInterpolatableTTFs
    glyphSets = preProcessor.process()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/preProcessor.py", line 196, in process
    remember_curve_type=self._rememberCurveType and self.inplace,
  File "/usr/local/lib/python3.7/site-packages/cu2qu/ufo.py", line 283, in fonts_to_quadratic
    raise IncompatibleFontsError(glyph_errors)
cu2qu.errors.IncompatibleFontsError: fonts contains incompatible glyphs: 'Dhook', 'Dhook.sc', 'aogonek.b', 'aturned.b', 'careof', 'kai'
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.otf]
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.ttf]
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.ttf]
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.otf]
mv: rename /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.otf to /Users/fgriessh/Desktop/source-sans-pro/target/VAR/SourceSansVariable-Roman.otf: No such file or directory
mv: rename /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.ttf to /Users/fgriessh/Desktop/source-sans-pro/target/VAR/SourceSansVariable-Roman.ttf: No such file or directory
rm: /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/.tb_*: No such file or directory
rm: /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_*/*.*tf: No such file or directory
Done with SourceSansVariable-Roman


SourceSansVariable-Italic
Generating temp UFO master(s)...
Building local otf's for master font paths...
makeotf [Note] Using features file at '/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_0/SourceSans_ExtraLight-Italic.temp.ufo/features.fea'.
makeotf [Note] adding the style Italic from fontinfo keyword.
makeotf [Note] setting the USE_TYPO_METRICS OS/2 fsSelection bit 7 from fontinfo keyword.
makeotf [Note] setting the WEIGHT_WIDTH_SLOPE_ONLY OS/2 fsSelection bit 8 from fontinfo keyword.
makeotf [Note] setting the OBLIQUE OS/2 fsSelection bit 9 from fontinfo keyword.
makeotfexe [FATAL] <SourceSansVariable-Italic> include file <../../familyVersion.fea> not found [SourceSans_ExtraLight-Italic.temp.ufo/../../../../familyTables.fea 2]
makeotf [Error] Failed to build output font file 'SourceSans_ExtraLight-Italic.otf'.

Error building OTF font for /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_0/SourceSans_ExtraLight-Italic.temp.ufo makeotf [Note] Using features file at '/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_0/SourceSans_ExtraLight-Italic.temp.ufo/features.fea'.
makeotf [Note] adding the style Italic from fontinfo keyword.
makeotf [Note] setting the USE_TYPO_METRICS OS/2 fsSelection bit 7 from fontinfo keyword.
makeotf [Note] setting the WEIGHT_WIDTH_SLOPE_ONLY OS/2 fsSelection bit 8 from fontinfo keyword.
makeotf [Note] setting the OBLIQUE OS/2 fsSelection bit 9 from fontinfo keyword.
makeotfexe [FATAL] <SourceSansVariable-Italic> include file <../../familyVersion.fea> not found [SourceSans_ExtraLight-Italic.temp.ufo/../../../../familyTables.fea 2]
makeotf [Error] Failed to build output font file 'SourceSans_ExtraLight-Italic.otf'.

makeotf cmd was 'makeotf -nshw -f "SourceSans_ExtraLight-Italic.temp.ufo" -o "SourceSans_ExtraLight-Italic.otf" -r -nS  2>&1' in /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_0.
makeotf [Note] Using features file at '/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_1/SourceSans_Black-Italic.temp.ufo/features.fea'.
makeotfexe [FATAL] <SourceSans_Black-Italic> include file <../../familyVersion.fea> not found [SourceSans_Black-Italic.temp.ufo/../../../../familyTables.fea 2]
makeotf [Error] Failed to build output font file 'SourceSans_Black-Italic.otf'.

Error building OTF font for /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_1/SourceSans_Black-Italic.temp.ufo makeotf [Note] Using features file at '/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_1/SourceSans_Black-Italic.temp.ufo/features.fea'.
makeotfexe [FATAL] <SourceSans_Black-Italic> include file <../../familyVersion.fea> not found [SourceSans_Black-Italic.temp.ufo/../../../../familyTables.fea 2]
makeotf [Error] Failed to build output font file 'SourceSans_Black-Italic.otf'.

makeotf cmd was 'makeotf -nshw -f "SourceSans_Black-Italic.temp.ufo" -o "SourceSans_Black-Italic.otf" -r -nS  2>&1' in /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_1.
Traceback (most recent call last):
  File "/usr/local/bin/buildcff2vf", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/afdko/buildcff2vf.py", line 989, in run
    otfFinder, exclude=("CFF2",))
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 779, in build
    master_fonts = load_masters(designspace, master_finder)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 893, in load_masters
    master.font = font = _open_font(master.path, master_finder)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 852, in _open_font
    raise VarLibError("Invalid master path: %r" % master_path)
fontTools.varLib.VarLibError: Invalid master path: '/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_0/SourceSans_ExtraLight-Italic.otf'
Subroutinizing SourceSansVariable-Italic.otf
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.otf]
INFO:ufo2ft:Pre-processing glyphs
ERROR:cu2qu.ufo:Glyphs named 'kadescender' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'lje' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'Ghestroke' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'zhedescender' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'kturned' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'hadescender' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'Dhook' have incompatible segment types:
  9: ('curve', 'line')
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontmake/__main__.py", line 395, in main
    project.run_from_designspace(designspace_path, **args)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 865, in run_from_designspace
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 919, in _run_from_designspace_interpolatable
    ttf_designspace = self.build_interpolatable_ttfs(designspace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 333, in build_interpolatable_ttfs
    return self._build_interpolatable_masters(designspace, ttf=True, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 318, in _build_interpolatable_masters
    inplace=True,
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 338, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 234, in compileInterpolatableTTFs
    glyphSets = preProcessor.process()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/preProcessor.py", line 196, in process
    remember_curve_type=self._rememberCurveType and self.inplace,
  File "/usr/local/lib/python3.7/site-packages/cu2qu/ufo.py", line 283, in fonts_to_quadratic
    raise IncompatibleFontsError(glyph_errors)
cu2qu.errors.IncompatibleFontsError: fonts contains incompatible glyphs: 'Dhook', 'Ghestroke', 'hadescender', 'kadescender', 'kturned', 'lje', 'zhedescender'
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.otf]
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.ttf]
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.ttf]
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.otf]
mv: rename /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.otf to /Users/fgriessh/Desktop/source-sans-pro/target/VAR/SourceSansVariable-Italic.otf: No such file or directory
mv: rename /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.ttf to /Users/fgriessh/Desktop/source-sans-pro/target/VAR/SourceSansVariable-Italic.ttf: No such file or directory
rm: /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/.tb_*: No such file or directory
rm: /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_*/*.*tf: No such file or directory
Done with SourceSansVariable-Italic


source-sans-pro$
```

**Comment by frankrolf** [comment]
when I check out the tag `2.045-ro/1.095-it`, running the script `./buildVFs.sh` fails like this:

```
$ cd ~/Desktop/source-sans-pro/
~/Desktop/source-sans-pro fgriessh (HEAD detached at df55324aa)
$ ./buildVFs.sh
SourceSansVariable-Roman
Building local otf's for master font paths...
Built OTF font for /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_0/SourceSans_ExtraLight.ufo
Built OTF font for /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_1/SourceSans_Black.ufo
Opening default font /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_0/SourceSans_ExtraLight.otf
Opening /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_1/SourceSans_Black.otf
Reading glyph data...
Adding STAT table
ERROR:fontTools.ttLib.tables.otTables:Don't know how to split GPOS lookup type 6
Built variable font '/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.otf'
Subroutinizing SourceSansVariable-Roman.otf
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths: 1: 40, 2: 2586, 3: 1391, 4: 161, 5: 14, 6: 16
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on SourceSansVariable-Roman
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on SourceSans_Black
INFO:ufo2ft:Building OpenType tables for SourceSansVariable-Roman
WARNING:ufo2ft.featureCompiler:Please change the file name in the include(...); statement to be relative to the UFO itself, instead of relative to the 'features.fea' file contained in it.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/lexer.py", line 230, in __next__
    self.lexers_.append(self.make_lexer_(path))
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/lexer.py", line 247, in make_lexer_
    fileobj = open(filename, "r", encoding="utf-8")
  File "/usr/local/lib/python3.7/site-packages/fontTools/misc/py23.py", line 250, in open
    file, mode, buffering, encoding, errors, newline, closefd)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_0/../../../../featuresVar.fea'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontmake/__main__.py", line 395, in main
    project.run_from_designspace(designspace_path, **args)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 865, in run_from_designspace
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 919, in _run_from_designspace_interpolatable
    ttf_designspace = self.build_interpolatable_ttfs(designspace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 333, in build_interpolatable_ttfs
    return self._build_interpolatable_masters(designspace, ttf=True, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 318, in _build_interpolatable_masters
    inplace=True,
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 338, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 259, in compileInterpolatableTTFs
    featureCompilerClass=featureCompilerClass,
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 440, in compileFeatures
    return featureCompiler.compile()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 125, in compile
    self.setupFeatures()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 222, in setupFeatures
    featureFile = parseLayoutFeatures(self.ufo)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 47, in parseLayoutFeatures
    parser = Parser(buf, glyphNames)
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 50, in __init__
    self.advance_lexer_(comments=True)
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 1606, in advance_lexer_
    self.next_token_location_) = next(self.lexer_)
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/lexer.py", line 235, in __next__
    raise IncludedFeaNotFound(fname_token, fname_location)
fontTools.feaLib.error.IncludedFeaNotFound: /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/master_0/SourceSans_ExtraLight.ufo:1:9: ../../../../featuresVar.fea
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.ttf]
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.ttf]
sfntedit [FATAL]: ./buildVFs.sh: line 15:  5186 Segmentation fault: 11  sfntedit -a cmap=$1/.tb_cmap,GDEF=$1/.tb_GDEF,GPOS=$1/.tb_GPOS,GSUB=$1/.tb_GSUB $1/$2.otf
mv: rename /Users/fgriessh/Desktop/source-sans-pro/Roman/Masters/SourceSansVariable-Roman.ttf to /Users/fgriessh/Desktop/source-sans-pro/target/VAR/SourceSansVariable-Roman.ttf: No such file or directory
Done with SourceSansVariable-Roman


SourceSansVariable-Italic
Building local otf's for master font paths...
Built OTF font for /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_0/SourceSans_ExtraLight-Italic.ufo
Built OTF font for /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_1/SourceSans_Black-Italic.ufo
Opening default font /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_0/SourceSans_ExtraLight-Italic.otf
Opening /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_1/SourceSans_Black-Italic.otf
Reading glyph data...
Adding STAT table
Built variable font '/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.otf'
Subroutinizing SourceSansVariable-Italic.otf
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths: 1: 45, 2: 1829, 3: 659, 4: 245, 5: 47, 6: 10
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on SourceSansVariable-Italic
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on SourceSans_Black-Italic
INFO:ufo2ft:Building OpenType tables for SourceSansVariable-Italic
WARNING:ufo2ft.featureCompiler:Please change the file name in the include(...); statement to be relative to the UFO itself, instead of relative to the 'features.fea' file contained in it.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/lexer.py", line 230, in __next__
    self.lexers_.append(self.make_lexer_(path))
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/lexer.py", line 247, in make_lexer_
    fileobj = open(filename, "r", encoding="utf-8")
  File "/usr/local/lib/python3.7/site-packages/fontTools/misc/py23.py", line 250, in open
    file, mode, buffering, encoding, errors, newline, closefd)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_0/../../../../featuresVar.fea'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontmake/__main__.py", line 395, in main
    project.run_from_designspace(designspace_path, **args)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 865, in run_from_designspace
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 919, in _run_from_designspace_interpolatable
    ttf_designspace = self.build_interpolatable_ttfs(designspace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 333, in build_interpolatable_ttfs
    return self._build_interpolatable_masters(designspace, ttf=True, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 318, in _build_interpolatable_masters
    inplace=True,
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 338, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 259, in compileInterpolatableTTFs
    featureCompilerClass=featureCompilerClass,
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 440, in compileFeatures
    return featureCompiler.compile()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 125, in compile
    self.setupFeatures()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 222, in setupFeatures
    featureFile = parseLayoutFeatures(self.ufo)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 47, in parseLayoutFeatures
    parser = Parser(buf, glyphNames)
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 50, in __init__
    self.advance_lexer_(comments=True)
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 1606, in advance_lexer_
    self.next_token_location_) = next(self.lexer_)
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/lexer.py", line 235, in __next__
    raise IncludedFeaNotFound(fname_token, fname_location)
fontTools.feaLib.error.IncludedFeaNotFound: /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/master_0/SourceSans_ExtraLight-Italic.ufo:1:9: ../../../../featuresVar.fea
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.ttf]
sfntedit [FATAL]: file error <No such file or directory> [/Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.ttf]
sfntedit [FATAL]: ./buildVFs.sh: line 15:  5231 Segmentation fault: 11  sfntedit -a cmap=$1/.tb_cmap,GDEF=$1/.tb_GDEF,GPOS=$1/.tb_GPOS,GSUB=$1/.tb_GSUB $1/$2.otf
mv: rename /Users/fgriessh/Desktop/source-sans-pro/Italic/Masters/SourceSansVariable-Italic.ttf to /Users/fgriessh/Desktop/source-sans-pro/target/VAR/SourceSansVariable-Italic.ttf: No such file or directory
Done with SourceSansVariable-Italic


~/Desktop/source-sans-pro fgriessh (HEAD detached at df55324aa)
$
```

**Comment by miguelsousa** [comment]
Okidoki. I'll have a look later today.

**Comment by miguelsousa** [comment]
The build process for the variable fonts was indeed quite broken.
I've committed the necessary fixes to a branch called `fixed-vfonts-build`. The fonts build fine with afdko v2.8.8 and fontmake v1.9.1.

Leave this issue open. I need to coordinate with @pauldhunt the merging of the fixes into `master`.

**Comment by miguelsousa** [comment]
The fixes are now in the `master` branch.
